chore: BROADBOT_GITHUB_TOKEN => GITHUB_TOKEN (#7)

diff --git a/.github/workflows/integration_tests.yml b/.github/workflows/integration_tests.yml
--- a/.github/workflows/integration_tests.yml
+++ b/.github/workflows/integration_tests.yml
@@ -1,4 +1,4 @@
-name: 'Integration Tests'
+name: "Integration Tests"
 
 #This github action runs all of Cromwell's integration tests.
 
@@ -10,7 +10,7 @@ on:
   workflow_dispatch: #Manual trigger from GitHub UI
   push:
   schedule:
-    - cron: '0 0 * * 1-5'
+    - cron: "0 0 * * 1-5"
   merge_group:
 
 permissions:
@@ -93,41 +93,41 @@ jobs:
     runs-on: ubuntu-latest
     timeout-minutes: 120
     steps:
-    - uses: sbt/setup-sbt@v1
-    - uses: actions/checkout@v3 # checkout the cromwell repo
-      with:
-        ref: ${{ inputs.target-branch }}
-    - uses: ./.github/set_up_cromwell_action #This github action will set up git-secrets, caching, java, and sbt.
-      with:
-        cromwell_repo_token: ${{ secrets.BROADBOT_GITHUB_TOKEN }}
-    # Activate SSH and idle for 30 minutes, see https://www.notion.so/SSH-into-Github-Action-287ab699a6f580609d01d3c88692df14 for details
-#    - name: Setup tmate session
-#      uses: mxschmitt/action-tmate@v3
-#      timeout-minutes: 30
-#      with:
-#        limit-access-to-actor: true
-#        detached: true
-    #This script bascially just looks up another script to run, assuming that the other script's filename is:
-    #src/ci/bin/test${BUILD_TYPE}.sh. The first letter of the BUILD_TYPE is automatically capitalized when looking.
-    - name: Run Integration Test
-      shell: 'script -q -e -c "bash --noprofile --norc -eo pipefail {0}"' #See comment below
-      run: |
-        set -e
-        echo Running test.sh
-        ./src/ci/bin/test.sh
-    - uses: codecov/codecov-action@v4
-      with:
-        token: ${{ secrets.CODECOV_TOKEN }}
-        fail_ci_if_error: false # Tolerate missing codecov reports, since not all suites generate them.
-    # always() is some github magic that forces the following step to run, even when the previous fails.
-    # Without it, the if statement won't be evaluated on a test failure.
-    - uses: ravsamhq/notify-slack-action@v2
-      if: always() && github.ref == 'refs/heads/develop' #only report on failures against develop.
-      with:
-        status: ${{ job.status }}
-        notify_when: "failure"
-      env:
-        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
+      - uses: sbt/setup-sbt@v1
+      - uses: actions/checkout@v3 # checkout the cromwell repo
+        with:
+          ref: ${{ inputs.target-branch }}
+      - uses: ./.github/set_up_cromwell_action #This github action will set up git-secrets, caching, java, and sbt.
+        with:
+          cromwell_repo_token: ${{ secrets.GITHUB_TOKEN }}
+      # Activate SSH and idle for 30 minutes, see https://www.notion.so/SSH-into-Github-Action-287ab699a6f580609d01d3c88692df14 for details
+      #    - name: Setup tmate session
+      #      uses: mxschmitt/action-tmate@v3
+      #      timeout-minutes: 30
+      #      with:
+      #        limit-access-to-actor: true
+      #        detached: true
+      #This script bascially just looks up another script to run, assuming that the other script's filename is:
+      #src/ci/bin/test${BUILD_TYPE}.sh. The first letter of the BUILD_TYPE is automatically capitalized when looking.
+      - name: Run Integration Test
+        shell: 'script -q -e -c "bash --noprofile --norc -eo pipefail {0}"' #See comment below
+        run: |
+          set -e
+          echo Running test.sh
+          ./src/ci/bin/test.sh
+      - uses: codecov/codecov-action@v4
+        with:
+          token: ${{ secrets.CODECOV_TOKEN }}
+          fail_ci_if_error: false # Tolerate missing codecov reports, since not all suites generate them.
+      # always() is some github magic that forces the following step to run, even when the previous fails.
+      # Without it, the if statement won't be evaluated on a test failure.
+      - uses: ravsamhq/notify-slack-action@v2
+        if: always() && github.ref == 'refs/heads/develop' #only report on failures against develop.
+        with:
+          status: ${{ job.status }}
+          notify_when: "failure"
+        env:
+          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
     #The "shell: ..."" line is a way to force the Github Action Runner to use a bash shell that thinks it has a TTY.
     #The issue and solution are described here: https://github.com/actions/runner/issues/241#issuecomment-842566950
     #This is only needed for ReferenceDiskManifestBuilderApp test.
